# Generated by Django 6.0 on 2025-12-16 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('designs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='category',
        ),
        migrations.AddField(
            model_name='template',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='catalog.subcategory'),
        ),
    ]
