# Generated by Django 6.0 on 2025-12-30 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_printspecs_anchor_point_printspecs_shape_and_more'),
        ('designs', '0003_remove_template_category_template_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        # Removed print_spec field to avoid dependency conflict with deleted PrintSpecs model
        # migrations.AddField(
        #     model_name='template',
        #     name='print_spec',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='catalog.printspecs'),
        # ),
        migrations.AddField(
            model_name='template',
            name='surface',
            field=models.CharField(default='front', max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='design_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TemplateElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=20)),
                ('default_text', models.CharField(blank=True, max_length=255)),
                ('default_image', models.ImageField(blank=True, null=True, upload_to='template_assets/')),
                ('x_percent', models.FloatField(default=50.0)),
                ('y_percent', models.FloatField(default=50.0)),
                ('max_width_percent', models.FloatField(default=80.0)),
                ('rotation', models.FloatField(default=0.0)),
                ('font_family', models.CharField(blank=True, max_length=100)),
                ('font_size', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='designs.template')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
