# Generated by Django 6.0 on 2025-12-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_template_locked_template_print_spec_template_surface_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='template',
        #     name='print_spec',
        # ),
    ]
