# Generated by Django 6.0 on 2025-12-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/')),
                ('type', models.CharField(max_length=50)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('resolution_dpi', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='fonts/')),
                ('weight', models.CharField(default='400', help_text='e.g. 400, 700, bold', max_length=50)),
                ('style', models.CharField(default='normal', help_text='italic, normal', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Design', max_length=255)),
                ('design_json', models.JSONField(help_text='Fabric.js or similar canvas state')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='previews/')),
                ('thumbnail_high_res', models.ImageField(blank=True, null=True, upload_to='previews/hq/')),
                ('version', models.IntegerField(default=1)),
                ('is_template', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('design_json', models.JSONField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
