# Generated by Django 6.0 on 2025-12-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_printspecs_anchor_point_printspecs_shape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakekeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakeke_product_id', models.CharField(help_text='ID of the product in Zakeke backoffice', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zakeke_mapping', to='catalog.product')),
            ],
        ),
    ]
