# Generated by Django 6.0 on 2026-02-26 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_invoice_orderstatushistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RazorpayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                ('amount_paisa', models.PositiveBigIntegerField(help_text='Amount in paisa (₹1 = 100 paisa)')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('method', models.CharField(blank=True, help_text='card, upi, netbanking, wallet, etc.', max_length=30)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('wallet', models.CharField(blank=True, max_length=50)),
                ('vpa', models.CharField(blank=True, help_text='UPI VPA e.g. user@upi', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_description', models.TextField(blank=True)),
                ('error_reason', models.CharField(blank=True, max_length=100)),
                ('amount_refunded_paisa', models.PositiveBigIntegerField(default=0)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_transaction', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Razorpay Order Created'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('signature_verified', 'Signature Verified'), ('signature_failed', 'Signature Verification Failed'), ('webhook_received', 'Webhook Received'), ('webhook_payment_captured', 'Webhook: Payment Captured'), ('webhook_payment_failed', 'Webhook: Payment Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_success', 'Refund Successful'), ('refund_failed', 'Refund Failed')], db_index=True, max_length=30)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('request_payload', models.JSONField(blank=True, help_text='Data sent to Razorpay', null=True)),
                ('response_payload', models.JSONField(blank=True, help_text='Data received from Razorpay', null=True)),
                ('is_success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to=settings.AUTH_USER_MODEL)),
                ('razorpay_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='orders.razorpaytransaction')),
            ],
            options={
                'verbose_name_plural': 'Payment logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PincodeServiceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('standard_available', models.BooleanField(default=True)),
                ('express_available', models.BooleanField(default=True)),
                ('priority_available', models.BooleanField(default=False)),
                ('cod_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='orders.shippingzone')),
            ],
            options={
                'verbose_name_plural': 'Pincode serviceability',
                'ordering': ['pincode'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery'), ('priority', 'Priority Delivery')], max_length=20)),
                ('min_weight_grams', models.PositiveIntegerField(default=0, help_text='Minimum weight in grams (inclusive)')),
                ('max_weight_grams', models.PositiveIntegerField(default=99999, help_text='Maximum weight in grams (inclusive)')),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Flat base charge in ₹', max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=0, help_text='Additional charge per kg above base weight', max_digits=10)),
                ('base_weight_grams', models.PositiveIntegerField(default=500, help_text='Weight included in base_rate; per_kg_rate applies above this')),
                ('free_above', models.DecimalField(blank=True, decimal_places=2, help_text='Order value above which shipping is free (₹). Leave blank = never free.', max_digits=10, null=True)),
                ('min_days', models.PositiveIntegerField(default=3)),
                ('max_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='orders.shippingzone')),
            ],
            options={
                'ordering': ['zone', 'method', 'min_weight_grams'],
                'unique_together': {('zone', 'method', 'min_weight_grams', 'max_weight_grams')},
            },
        ),
    ]
