# Generated by Django 6.0 on 2026-02-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shippingzone_razorpaytransaction_paymentlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='design_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Design/customization price from Zakeke', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='high_res_design_url',
            field=models.URLField(blank=True, help_text='High-resolution print file URL from Zakeke'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='zakeke_design_id',
            field=models.CharField(blank=True, help_text='Zakeke design ID for this item', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='awb_code',
            field=models.CharField(blank=True, db_index=True, help_text='Air Waybill number from courier', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier_name',
            field=models.CharField(blank=True, help_text='Courier partner name from Shiprocket', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shiprocket_shipment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('label_created', 'Label Created'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('rto_initiated', 'RTO Initiated'), ('rto_delivered', 'RTO Delivered'), ('cancelled', 'Cancelled'), ('lost', 'Lost')], default='label_created', max_length=50),
        ),
        migrations.CreateModel(
            name='ShipmentTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='e.g. In Transit, Out for Delivery', max_length=100)),
                ('status_code', models.CharField(blank=True, help_text='Shiprocket status code', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed event description')),
                ('location', models.CharField(blank=True, help_text='City/Hub where scan occurred', max_length=255)),
                ('event_time', models.DateTimeField(help_text='When the event occurred at the courier')),
                ('raw_data', models.JSONField(blank=True, help_text='Raw API response for this event', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='orders.shipment')),
            ],
            options={
                'verbose_name_plural': 'Shipment tracking events',
                'ordering': ['-event_time'],
            },
        ),
    ]
