# Generated by Django 6.0 on 2026-03-12 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_design_price_orderitem_high_res_design_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='razorpay_transaction',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='instamojo_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='instamojo_payment_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Payment Request Created'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('signature_verified', 'Payment Verified'), ('signature_failed', 'Payment Verification Failed'), ('webhook_received', 'Webhook Received'), ('webhook_payment_captured', 'Webhook: Payment Captured'), ('webhook_payment_failed', 'Webhook: Payment Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_success', 'Refund Successful'), ('refund_failed', 'Refund Failed')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='request_payload',
            field=models.JSONField(blank=True, help_text='Data sent to Instamojo', null=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='response_payload',
            field=models.JSONField(blank=True, help_text='Data received from Instamojo', null=True),
        ),
        migrations.CreateModel(
            name='InstamojoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instamojo_payment_request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('instamojo_payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in ₹', max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('longurl', models.URLField(blank=True, help_text='Instamojo payment URL')),
                ('method', models.CharField(blank=True, help_text='card, upi, netbanking, wallet, etc.', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_description', models.TextField(blank=True)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instamojo_transaction', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instamojo_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='instamojo_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='orders.instamojotransaction'),
        ),
        migrations.DeleteModel(
            name='RazorpayTransaction',
        ),
    ]
