# Generated by Django 6.0 on 2026-03-15 19:23

import django.db.models.deletion
import shop_project.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_paymentlog_razorpay_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_abandonment_enabled', models.BooleanField(default=True)),
                ('cart_abandonment_delay_minutes', models.IntegerField(default=60, help_text='Minutes after cart becomes idle to trigger reminder')),
                ('cart_abandonment_max_reminders', models.IntegerField(default=3)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_api_provider', models.CharField(blank=True, help_text='e.g., twilio, wati, interakt, gupshup', max_length=50)),
                ('email_campaigns_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing Settings',
                'verbose_name_plural': 'Marketing Settings',
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=shop_project.storage_backends.PrivateMediaStorage(), upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='print_file_url',
            field=models.FileField(blank=True, null=True, storage=shop_project.storage_backends.PrivateMediaStorage(), upload_to='print_files/'),
        ),
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data', models.JSONField(help_text='Snapshot of cart items: [{product_id, name, quantity, price, image}]')),
                ('cart_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('abandoned', 'Abandoned'), ('reminder_sent', 'Reminder Sent'), ('recovered', 'Recovered'), ('expired', 'Expired')], default='abandoned', max_length=20)),
                ('reminder_count', models.IntegerField(default=0, help_text='Number of reminders sent')),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('abandoned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovered_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_from_cart', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-abandoned_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal campaign name', max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email + WhatsApp')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual Send'), ('cart_abandonment', 'Cart Abandonment'), ('order_followup', 'Order Follow-up'), ('welcome', 'Welcome New User'), ('inactive_user', 'Re-engage Inactive User'), ('product_restock', 'Product Back in Stock')], default='manual', max_length=30)),
                ('subject', models.CharField(blank=True, help_text='Email subject line', max_length=255)),
                ('email_body', models.TextField(blank=True, help_text='HTML email body')),
                ('whatsapp_message', models.TextField(blank=True, help_text='WhatsApp message template')),
                ('target_all_users', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_opened', models.IntegerField(default=0)),
                ('emails_clicked', models.IntegerField(default=0)),
                ('whatsapp_sent', models.IntegerField(default=0)),
                ('whatsapp_delivered', models.IntegerField(default=0)),
                ('whatsapp_read', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email + WhatsApp')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
