# Generated by Django 6.0 on 2025-12-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_discount_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.URLField(blank=True, help_text='S3 URL for primary image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(help_text='S3 URL for product image', max_length=500),
        ),
    ]
