# Generated by Django 6.0 on 2025-12-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_primary_image_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.URLField(help_text='S3 URL for banner image', max_length=500)),
                ('placement', models.CharField(choices=[('hero_primary', 'Hero Primary Section'), ('hero_secondary', 'Hero Secondary Section'), ('homepage', 'Homepage General'), ('category', 'Category Page')], default='homepage', max_length=20)),
                ('buttons_json', models.JSONField(blank=True, default=list, help_text='JSON array of button objects')),
                ('footer_text', models.CharField(blank=True, help_text='Optional footer text with breadcrumb', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['placement', 'display_order', '-created_at'],
            },
        ),
    ]
