# Generated by Django 6.0 on 2025-12-30 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='printspecs',
            name='anchor_point',
            field=models.CharField(choices=[('center', 'Center'), ('top-center', 'Top Center'), ('bottom-center', 'Bottom Center'), ('custom', 'Custom')], default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='printspecs',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('curved', 'Curved')], default='rectangle', max_length=50),
        ),
        migrations.AddField(
            model_name='printspecs',
            name='surface',
            field=models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left', 'Left'), ('right', 'Right')], default='front', max_length=50),
        ),
        migrations.AddField(
            model_name='printspecs',
            name='x_percent',
            field=models.FloatField(default=50.0, help_text='Horizontal anchor relative to mockup (%)'),
        ),
        migrations.AddField(
            model_name='printspecs',
            name='y_percent',
            field=models.FloatField(default=50.0, help_text='Vertical anchor relative to mockup (%)'),
        ),
        migrations.AlterField(
            model_name='printspecs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_specs_list', to='catalog.product'),
        ),
    ]
