# Generated by Django 6.0 on 2026-02-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_printspecs_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(default=200, help_text='Product weight in grams for shipping calculation'),
        ),
    ]
