# Generated by Django 6.0 on 2026-03-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this product was ordered'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this product page was viewed'),
        ),
    ]
