# Generated by Django 6.0 on 2025-12-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_printspecs_anchor_point_printspecs_shape_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='printspecs',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='productattribute',
                    name='product',
                ),
                migrations.DeleteModel(
                    name='AttributeValue',
                ),
                migrations.DeleteModel(
                    name='PrintSpecs',
                ),
                migrations.DeleteModel(
                    name='ProductAttribute',
                ),
            ],
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS catalog_printspecs CASCADE;"),
                migrations.RunSQL("DROP TABLE IF EXISTS catalog_productattribute CASCADE;"),
                migrations.RunSQL("DROP TABLE IF EXISTS catalog_attributevalue CASCADE;"),
            ]
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_kg',
        ),
    ]
