# Generated by Django 6.0 on 2026-03-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title displayed at the top', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto-generated from title)', max_length=200, unique=True)),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions'), ('cookies', 'Cookie Policy'), ('refund', 'Refund Policy'), ('shipping', 'Shipping Policy'), ('about', 'About Us'), ('contact', 'Contact Us'), ('faq', 'FAQ'), ('custom', 'Custom Page')], default='custom', help_text='Type of page', max_length=20)),
                ('content', models.TextField(help_text='Page content (HTML supported)')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=300)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
                'ordering': ['title'],
            },
        ),
    ]
