# Generated by Django 6.0.3 on 2026-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Offer text displayed in the marquee (e.g. 'Flat 20% off on T-shirts')", max_length=200)),
                ('icon', models.CharField(default='🔥', help_text='Emoji icon shown before the offer text', max_length=10)),
                ('link', models.CharField(blank=True, default='', help_text='Optional link when user clicks the offer', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this offer')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
