# Generated by Django 6.0 on 2026-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title (internal reference)', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional subtitle or tagline', max_length=300)),
                ('image_url', models.URLField(help_text='Full URL to the banner image (e.g. S3 or CDN link)', max_length=1000)),
                ('mobile_image_url', models.URLField(blank=True, default='', help_text='Optional mobile-specific image URL', max_length=1000)),
                ('link', models.CharField(blank=True, default='', help_text='URL to navigate when banner is clicked', max_length=500)),
                ('position', models.CharField(choices=[('hero', 'Hero Banner (Homepage)'), ('promo', 'Promotional Banner'), ('sidebar', 'Sidebar Banner'), ('category', 'Category Page Banner'), ('popup', 'Popup Banner')], default='hero', help_text='Where the banner appears on the site', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this banner')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first in that position')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional: banner becomes visible after this date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional: banner is hidden after this date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['position', 'display_order', '-created_at'],
            },
        ),
    ]
