# Generated by Django 6.0 on 2026-03-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Customer name', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount (₹)', max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('pending', 'Pending')], default='received', max_length=10)),
                ('note', models.CharField(blank=True, default='', help_text='Invoice number, description, etc.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offline Payment',
                'verbose_name_plural': 'Offline Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Promo code (e.g. WELCOME20)', max_length=30, unique=True)),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('flat', 'Flat Amount Discount')], default='percentage', max_length=12)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage 0-100 or flat amount in ₹)', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order subtotal to use this code', max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Max discount cap for percentage codes (₹)', max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='Max total uses (0 = unlimited)')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='How many times this code has been used')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Code becomes active after this datetime', null=True)),
                ('valid_to', models.DateTimeField(blank=True, help_text='Code expires after this datetime', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
