# Generated by Django 6.0 on 2026-03-18 15:41

from django.db import migrations, models, connection


def create_offline_payment_if_needed(apps, schema_editor):
    """Create pages_offlinepayment table only if it doesn't already exist."""
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'pages_offlinepayment')"
        )
        exists = cursor.fetchone()[0]
    if not exists:
        schema_editor.execute("""
            CREATE TABLE "pages_offlinepayment" (
                "id" bigserial NOT NULL PRIMARY KEY,
                "customer_name" varchar(200) NOT NULL,
                "amount" numeric(12,2) NOT NULL,
                "payment_method" varchar(20) NOT NULL DEFAULT 'cash',
                "status" varchar(10) NOT NULL DEFAULT 'received',
                "note" varchar(500) NOT NULL DEFAULT '',
                "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
                "updated_at" timestamp with time zone NOT NULL DEFAULT NOW()
            )
        """)


def create_promocode_if_needed(apps, schema_editor):
    """Create pages_promocode table only if it doesn't already exist."""
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'pages_promocode')"
        )
        exists = cursor.fetchone()[0]
    if not exists:
        schema_editor.execute("""
            CREATE TABLE "pages_promocode" (
                "id" bigserial NOT NULL PRIMARY KEY,
                "code" varchar(30) NOT NULL UNIQUE,
                "description" varchar(200) NOT NULL DEFAULT '',
                "discount_type" varchar(12) NOT NULL DEFAULT 'percentage',
                "discount_value" numeric(10,2) NOT NULL,
                "min_order_amount" numeric(10,2) NOT NULL DEFAULT 0,
                "max_discount" numeric(10,2) NULL,
                "usage_limit" integer NOT NULL DEFAULT 0 CHECK ("usage_limit" >= 0),
                "times_used" integer NOT NULL DEFAULT 0 CHECK ("times_used" >= 0),
                "valid_from" timestamp with time zone NULL,
                "valid_to" timestamp with time zone NULL,
                "is_active" boolean NOT NULL DEFAULT true,
                "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
                "updated_at" timestamp with time zone NOT NULL DEFAULT NOW()
            )
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_banner'),
    ]

    operations = [
        migrations.RunPython(
            create_offline_payment_if_needed,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            create_promocode_if_needed,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
